apiVersion: apps/v1
kind: Deployment
metadata:
  name: weathers
  labels:
    app: weathers
spec:
  replicas: 3	 	# three pod
  selector:
    matchLabels:
      app: weathers
  template:
    metadata:
      labels:
        app: weathers
    spec:
      containers:
      - name: weathers
        image: minseoplee/weathers
        ports:
        - containerPort: 8000	 # container port (pod port)
